title: Evaristo Villaseco # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a physicist driven by a passion for understanding, modeling, and explaining the world around me. My PhD research, at the intersection of chemistry and physics, focused on developing efficient and accurate algorithms to simulate photochemical processes. 

  <br><br>
 I enjoy solving real-world problems through data-driven modeling, applying my skills across diverse domains. Beyond modeling the fundamental interactions driving photochemistry, I have worked on projects ranging from predicting La Liga match outcomes to optimizing restaurant supply classification.

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

